Project/Forum/Forum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Project/Forum/Forum/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forum.Controllers
{
    public class SessionController : Controller
    {
        public ActionResult LogIn()
        {
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Register()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

Project/Forum/Forum/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <div id="Header" style="background-color:darkseagreen; display:flex; justify-content:space-between">
            <div id="Logo" style="">
                GameDev.ua
            </div>
            <div id="Registration form" style="">
                @Html.TextBox("Log In")
                @Html.TextBox("Password")
                @Html.ActionLink("Log In", "LogIn", "Session")
                @Html.ActionLink("Register", "Register", "Session")
            </div>
        </div>
        <div id="Menu" style="background-color:darkorchid">
            Menu
        </div>
        <div id="Info" style="background-color:darkgreen">
            Info
        </div>
        <div style="display:flex; justify-content:space-between">
            <div>
                <div id="Map" style="background-color:burlywood; width:200px;">
                    Home<br />
                    Administrating<br />
                    Communities<br />
                    News<br />
                    Articles<br />
                    Forum<br />
                </div>
            </div>
            <div id="Content" style="background-color:brown">
                sdflksdgjk nsdlkjfgnl ksdnkg nsdkfngj nsdfngjs djfgn lksdnf gjsldkfgn sdljkfn gjklsdnfgjl
                knsdflkgn lsdkfngl ksndflkgn lsdfjgksdnfgjkl sndlkfgn ljskdfng klsdnfgkl nsdlkfgn
                ksldfng klsdnfkg nksdl gksndkg njklsdfng jksdnlj fgn sdjklfng jklsdfnglk sdnfklgn sdklfgn ksldgk lnsdlkg nsdkljfng lksdnfgkl nds g
                sdflksdgjk nsdlkjfgnl ksdnkg nsdkfngj nsdfngjs djfgn lksdnf gjsldkfgn sdljkfn gjklsdnfgjl
                knsdflkgn lsdkfngl ksndflkgn lsdfjgksdnfgjkl sndlkfgn ljskdfng klsdnfgkl nsdlkfgn
                ksldfng klsdnfkg nksdl gksndkg njklsdfng jksdnlj fgn sdjklfng jklsdfnglk sdnfklgn sdklfgn ksldgk lnsdlkg nsdkljfng lksdnfgkl nds g
                sdflksdgjk nsdlkjfgnl ksdnkg nsdkfngj nsdfngjs djfgn lksdnf gjsldkfgn sdljkfn gjklsdnfgjl
                knsdflkgn lsdkfngl ksndflkgn lsdfjgksdnfgjkl sndlkfgn ljskdfng klsdnfgkl nsdlkfgn
                ksldfng klsdnfkg nksdl gksndkg njklsdfng jksdnlj fgn sdjklfng jklsdfnglk sdnfklgn sdklfgn ksldgk lnsdlkg nsdkljfng lksdnfgkl nds g
                sdflksdgjk nsdlkjfgnl ksdnkg nsdkfngj nsdfngjs djfgn lksdnf gjsldkfgn sdljkfn gjklsdnfgjl
                knsdflkgn lsdkfngl ksndflkgn lsdfjgksdnfgjkl sndlkfgn ljskdfng klsdnfgkl nsdlkfgn
                ksldfng klsdnfkg nksdl gksndkg njklsdfng jksdnlj fgn sdjklfng jklsdfnglk sdnfklgn sdklfgn ksldgk lnsdlkg nsdkljfng lksdnfgkl nds g
            </div>
        </div>
    </div>
</body>
</html>